//------------------------------------------------------------------------------
<<<<<<< HEAD
<<<<<<< HEAD
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
=======
=======
>>>>>>> cdad350de922c2dc1de3ee5ee23e74969f7578b1
// <generado automáticamente>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código. 
// </generado automáticamente>
<<<<<<< HEAD
>>>>>>> cdad350... New working project by Leiscar
=======
>>>>>>> cdad350de922c2dc1de3ee5ee23e74969f7578b1
//------------------------------------------------------------------------------

namespace LoginApplication
{


    public partial class Login
    {

        /// <summary>
<<<<<<< HEAD
<<<<<<< HEAD
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
=======
=======
>>>>>>> cdad350de922c2dc1de3ee5ee23e74969f7578b1
        /// Control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
<<<<<<< HEAD
>>>>>>> cdad350... New working project by Leiscar
=======
>>>>>>> cdad350de922c2dc1de3ee5ee23e74969f7578b1
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
<<<<<<< HEAD
<<<<<<< HEAD
        /// Label1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
=======
=======
>>>>>>> cdad350de922c2dc1de3ee5ee23e74969f7578b1
        /// Control Label1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
<<<<<<< HEAD
>>>>>>> cdad350... New working project by Leiscar
=======
>>>>>>> cdad350de922c2dc1de3ee5ee23e74969f7578b1
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label1;

        /// <summary>
<<<<<<< HEAD
<<<<<<< HEAD
        /// TextBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
=======
=======
>>>>>>> cdad350de922c2dc1de3ee5ee23e74969f7578b1
        /// Control TextBox1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
<<<<<<< HEAD
>>>>>>> cdad350... New working project by Leiscar
=======
>>>>>>> cdad350de922c2dc1de3ee5ee23e74969f7578b1
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TextBox1;

        /// <summary>
<<<<<<< HEAD
<<<<<<< HEAD
        /// Label2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
=======
=======
>>>>>>> cdad350de922c2dc1de3ee5ee23e74969f7578b1
        /// Control Label2.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
<<<<<<< HEAD
>>>>>>> cdad350... New working project by Leiscar
=======
>>>>>>> cdad350de922c2dc1de3ee5ee23e74969f7578b1
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label2;

        /// <summary>
<<<<<<< HEAD
<<<<<<< HEAD
        /// TextBox2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
=======
=======
>>>>>>> cdad350de922c2dc1de3ee5ee23e74969f7578b1
        /// Control TextBox2.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
<<<<<<< HEAD
>>>>>>> cdad350... New working project by Leiscar
=======
>>>>>>> cdad350de922c2dc1de3ee5ee23e74969f7578b1
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TextBox2;

        /// <summary>
<<<<<<< HEAD
<<<<<<< HEAD
        /// Button1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
=======
=======
>>>>>>> cdad350de922c2dc1de3ee5ee23e74969f7578b1
        /// Control Button1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
<<<<<<< HEAD
>>>>>>> cdad350... New working project by Leiscar
=======
>>>>>>> cdad350de922c2dc1de3ee5ee23e74969f7578b1
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button1;

        /// <summary>
<<<<<<< HEAD
<<<<<<< HEAD
        /// Button2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button2;

        /// <summary>
        /// Label3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
=======
=======
>>>>>>> cdad350de922c2dc1de3ee5ee23e74969f7578b1
        /// Control Label3.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
<<<<<<< HEAD
>>>>>>> cdad350... New working project by Leiscar
=======
>>>>>>> cdad350de922c2dc1de3ee5ee23e74969f7578b1
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label3;
    }
}
