//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginTestNexus
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegTable
    {
        public int Id { get; set; }
        public string NombreUsuario { get; set; }
        public string PrimerNombre { get; set; }
        public string Apellidos { get; set; }
        public string Genero { get; set; }
        public string Email { get; set; }
        public string Ciudad { get; set; }
        public string NumTelefono { get; set; }
        public string ClaveAcceso { get; set; }
        public string Cedula { get; set; }
    }
}
